version: "3.8"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432"
    restart: always
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - postgresdb
    ports:
      - "8084:80"
    volumes:
      - ./static/:/static
    restart: always

volumes:
  postgres_data: